### ISSUE TITLE
When tests fail exit with 0

### ISSUE THREAD

**Issue by felipegs** [sindresorhus/gulp-jasmine#34]
When I use gulp-jasmine if the test fails the process exit with code 0, but it should be 1.

**Comment by Nijikokun** [comment]
No failure reporter? If you are going to compare to how `jshint` handles this, they have a failure reporter.

**Comment by andyp1per** [comment]
This is definitely a bug in gulp-jasmine 2.x IMO. I did not see this failure in 1.x

return gulp.src(...).pipe(jasmine(...)); does not work - failing tests do not fail gulp:

return gulp.src(...).pipe(jasmine(...)).on('error', function (err) {
            done(err);
        }); does work however, but should not be necessary
