### ISSUE TITLE
Add support for captureExceptions

### ISSUE THREAD

**Issue by mpj** [sindresorhus/gulp-jasmine#39]
Right now I use the 'jasmine-async-errors' to work around the problem, but jasmine has a setting for it that should work, but doesn't seem to work in gulp-jasmine. This is what I'd like to work:

```javascript
      .pipe(jasmine({
        captureExceptions: true
      }));
```
(to be clear, this is the issue I'm trying to solve: https://github.com/mhevery/jasmine-node/issues/267#issuecomment-26523453)

**Comment by jbblanchet** [comment]
This seems like a setting on jasmine-node, not on jasmine itself. gulp-jasmine uses [jasmine-npm](https://github.com/jasmine/jasmine-npm). I don't think such a setting exists in that project.

**Comment by jbblanchet** [comment]
Closed for inactivity.
