### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by Hiswe** [sindresorhus/gulp-jasmine#45]
Hi,

I have this issue while running gulp-jasmine:

```
[11:49:37] Error in plugin 'gulp-jasmine'
Message:
    Module did not self-register.
```

with node v0.12.0 and npm 2.7.1
I've seen that node 0.12 might be the problem (like with [node-sass](https://github.com/sass/node-sass/issues/653)) 

I hope you'll be able to fix because I was really enjoying using your gulp plugin :)

**Comment by kevva** [comment]
Try removing `node_modules` and run `npm install` again.

**Comment by Hiswe** [comment]
I feel shameful. 
It works again :) thank you!
