### ISSUE TITLE
Explain what gulp-jasmine does in the readme

### ISSUE THREAD

**Issue by tkrotoff** [sindresorhus/gulp-jasmine#46]
It is unclear what gulp-jasmine does. So i've tried it and got: `window is not defined`.

I believe gulp-jasmine runs Jasmine through Node.js and thus is not suitable for client side testing.
A mention on the readme explaining "works only for server side code" would be nice.

**Comment by jasonwr** [comment]
What's the benefit of using gulp-jasmine if the Jasmine framework can be pulled directly into the karma.config.js file? I don't see a reason to use it. Just set this in Karma and let Gulp call it.

**Comment by jbblanchet** [comment]
@jasonwr And if you don't need Karma?

**Comment by jasonwr** [comment]
@jbblanchet I don't understand "And if you don't need Karma?" Karma is the test runner.

**Comment by jbblanchet** [comment]
Karma is one of many test runners, and you're free to use it. But it's not the only one. The easiest example is if you need to test server code. Why use Karma? Just use gulp-jasmine, your tests will run quicker and you'll have one less dependency.

**Comment by jasonwr** [comment]
I’m using gulp-jasmine for the server side tests and Karma for the front-end tests. This works fine for me. There’s a lot of community support and documentation for Karma.
