### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by gbbr** [sindresorhus/gulp-jasmine#47]
Sorry to open an issue for more of a question, but I can't find a solution to an issue I'm having.

I'm trying to use `gulp-jasmine` to run my test suite which imports scripts that contain JSX and ES6 code. I can't find any way to add a preprocessor, I've tried passing your module options as you would to a normal jasmine configuration with preprocessors (using babel), but no luck. Ideally I'd like to use my custom preprocessing function which runs `ReactTools.transform` under the hood but I'm open to _any_ other solutions too.

Would be much appreciated if you could help out.

**Comment by jbblanchet** [comment]
Hi,

Sorry for the delay. I'm not sure this is a gulp-jasmine issue. This is similar to what we do with TypeScript. I think you should process your files using a build task, and load these files in your tests. Does that make sense?

**Comment by arthurvr** [comment]
> I'm not sure this is a gulp-jasmine issue. This is similar to what we do with TypeScript. I think you should process your files using a build task, and load these files in your tests. Does that make sense?

Yes.
