### ISSUE TITLE
Running tests inside watch ends watch

### ISSUE THREAD

**Issue by robations** [sindresorhus/gulp-jasmine#50]
When I execute gulp-jasmine inside a watch the watch stops after the first test run. I'd expect it to continue watching and keep running tests whenever the appropriate files change. Sample gulp code:

```
...
gulp.task('test', ['compile'], function () {
    return gulp.src('build/tests/**/*.spec.js')
        .pipe(jasmine());
});

gulp.task('watch', ['default'], function () {
    gulp.watch(['src/**/*.ts', 'tests/**/*.ts'], ['default']);
});
```

Sample output:

```
[11:51:19] Finished 'compile' after 4.49 s
[11:51:19] Starting 'test'...
.............................................

45 specs, 0 failures
Finished in 0 seconds
myprompt$

```

I'm fairly new to node style Javascript so possible I've misunderstood something.

**Comment by 360disrupt** [comment]
Where do you call test? Why not 
```
gulp.task('watch', ['default'], function () {
    gulp.watch(['src/**/*.ts', 'tests/**/*.ts'], ['default', 'test']);
});
```
and call ```gulp watch```

**Comment by robations** [comment]
Sorry, should have added this info:

'default' depends on ['compile', 'test']
'watch' depends on \['default'\] (in case there are pending changes when you first call `gulp watch`)

But if I do `gulp.watch(..., ['test'])` there is still the same behaviour - that the process finishes.

**Comment by jbblanchet** [comment]
I've tested your scenario, and there appears to be a bug when using the newly released jasmine 2.3 where gulp-jasmine doesn't end properly. I'll open an issue for that. In the mean time, could you test using jasmine@2.2.0 (inside node_modules/gulp-jasmine, delete node_modules, update the jasmine version in package.json to 2.2.0 and rerun npm install), and validate that this is indeed the issue you're facing?

Thanks.

**Comment by robations** [comment]
Thanks for checking this out. I tried downgrading to jasmine@2.2.0 as you describe and this does fix the issue. Let me know if you need any more info.

**Comment by jbblanchet** [comment]
Thanks for reporting this issue and confirming that it's confined to jasmine 2.3. I'll close this issue since it is not a problem with gulp.watch but with the jasmine update. They appear to be preparing a patch right now. I'll update issue #51 when the situation is fixed.
