### ISSUE TITLE
gulp-jasmine does not end properly with jasmine 2.3

### ISSUE THREAD

**Issue by jbblanchet** [sindresorhus/gulp-jasmine#51]
### test.spec.js:
```
describe("a test", function() {
    it("runs", function () {
        expect(1).toBe(1); 
    });
});
```

### gulpfile.js:
```
gulp.task('test', function () {
    return gulp.src('test.spec.js')
        .pipe(jasmine());
});
```

### run `gulp test`

Process ends unexpectedly after running the test, but is fine with jasmine 2.2.

**Comment by jbblanchet** [comment]
See [this issue](https://github.com/jasmine/jasmine-npm/issues/43).

**Comment by jbblanchet** [comment]
Solved by jasmine 2.3.1.

**Comment by normanwenk** [comment]
I have that issue with jasmine 2.5.3.
Downgrading to 2.2.0 solves it.

I use very simple setup with gulp-jasmine 2.3.0.

**Comment by jbblanchet** [comment]
@normanwenk Example above works perfectly with jasmine 2.5.3, so it is not the same issue. Please fill in a separate issue, with a way to reproduce the error so we can investigate. Thanks.
