### ISSUE TITLE
Bump Jasmine to 2.3.4 to resolve hotfix bug.

### ISSUE THREAD

**Issue by JasonCust** [sindresorhus/gulp-jasmine#52]
Please refer to: https://github.com/jasmine/jasmine/issues/850

**Comment by sindresorhus** [comment]
Lol, this is the 7th time I paste this blog post today. Seems like no-one knows how semver works...

https://nodesource.com/blog/semver-tilde-and-caret

**Comment by JasonCust** [comment]
@sindresorhus I understand semver but for some reason this is the dependency tree I get when specifying gulp-jasmine as '^2.0.1':

    gulp-jasmine@2.0.1 node_modules/gulp-jasmine
    ├── jasmine-terminal-reporter@0.9.1
    ├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
    └── jasmine@2.3.1 (exit@0.1.2, jasmine-core@2.3.4, glob@3.2.11)

I see the package in gulp-jasmine specifies jasmine as '^2.1.0' so I guess it might be they haven't published to npm yet?
