### ISSUE TITLE
Error  TypeError: Object #<Object> has no method 'addMatchers'

### ISSUE THREAD

**Issue by donnrri** [sindresorhus/gulp-jasmine#57]
When creating custom matcher the following error is seen
 TypeError: Object #<Object> has no method 'addMatchers'

here is my code 

 beforeEach(function() {
   calc = new Calculator();

    this.addMatchers({

      toBeTwo: function(){

        this.message = function(){

          return this.actual + " is not two";
        }
return this.actual === 2;
      }
    });

  });

**Comment by jbblanchet** [comment]
Your syntax is for jasmine 1.3. See the latest jasmine [documentation](http://jasmine.github.io/2.3/custom_matcher.html) for a correct implementation.

**Comment by donnrri** [comment]
Doh ! Of course. Thanks , sorry for taking up your time.
