### ISSUE TITLE
export jasmine object

### ISSUE THREAD

**Issue by DmitryEfimenko** [sindresorhus/gulp-jasmine#75]
Sometimes it's convenient to access `jasmine` object directly and set it up however you need it.
My use case is that I want to use [fail-fast](https://github.com/Updater/jasmine-fail-fast). If `jasmine` object was exported, I could write a gulp task like below:
```javascript
var $ = require('gulp-load-plugins')();

gulp.task('test', () => {
    var failFast = require('jasmine-fail-fast');
    $.jasmine.jasmine.getEnv().addReporter(failFast.init());
    return gulp.src('./spec/*.js')
        .pipe($.jasmine({ verbose: true }));
});
```
Exporting `jasmine` object would be a two line code change.
I can submit a PR if you give me a "good to go".

**Comment by jbblanchet** [comment]
Can't you just add it as a reporter in the options?

**Comment by DmitryEfimenko** [comment]
I'd like to use default terminal reporter that comes with `jasmine` dependency.
If I write this:
```javascript
.pipe($.jasmine({ verbose: true, reporter: failFast.init() }))
```
it'll override the default reporters.
I'd have to install terminal reporter separately and add it to array.

**Comment by jbblanchet** [comment]
I still think that it's preferable to exporting the jasmine object, especially since we are creating a new instance when you call $.jasmine(), so we couldn't export it before. I don't see a strong case for having 2 ways of adding reporters or configuring jasmine. Closing for now, feel free to discuss here some more if you feel differently.

**Comment by DmitryEfimenko** [comment]
That's fine. Indeed it's not a strong case. Maybe it'll be worth reconsidering if other people feel the need in this for some different reasons.

**Comment by DmitryEfimenko** [comment]
Actually that didn't work:
```javascript
var failFast = require('jasmine-fail-fast');
var Reporter = require('jasmine-terminal-reporter');

var terminalReporter = new Reporter({
    isVerbose: true,
    showColors: true,
    includeStackTrace: false 
});

return gulp.src('./spec/*.js')
        .pipe($.jasmine({ reporter: [terminalReporter, failFast.init()] }));
```
The `failFast.init()` expects a [global variable `jasmine`](https://github.com/Updater/jasmine-fail-fast/blob/master/src/index.js#L31). It's probably not a design flaw. At least I'm not sure how I'd tweak `failFast` to avoid this issue.

Basically I don't know how to make this work without exporting `jasmine` from `gulp-jasmine`.

**Comment by jbblanchet** [comment]
And how about you implement it as a helper (https://github.com/Updater/jasmine-fail-fast#as-a-jasmine-helper)?

I'm not sure it'll work, I'm not that familiar with helpers, but I think helpers give you access to the jasmine instance.

**Comment by DmitryEfimenko** [comment]
my understanding is that helpers are just a way of configuring the global `jasmine` object.
However, `gulp-jasmine` ignores global `jasmine` object. It creates a new instance of `Jasmine`.

Perhaps the whole thing would work if [variable `jasmine`](https://github.com/sindresorhus/gulp-jasmine/blob/master/index.js#L29) inside `gulp-jasmine` was declared like that:
```javascript
var jasmine = jasmine || new Jasmine();
```
This way if there is a global `jasmine` variable, it'd be used instead of a fresh instance.

**Comment by jbblanchet** [comment]
@DmitryEfimenko My understanding is that helpers are 'reinstalled' every time we call `jasmine.execute` on te jasmine instance. That's the reason we are clearing them first. Let me know if you've tried it and it didn't work, but I'm pretty sure it should.

**Comment by DmitryEfimenko** [comment]
you are right. I misunderstood what helpers are. It all worked.
For anyone who might need it, this is what the code looks like for me (besides adding the actual helper):
```javascript
var terminalReporter = new TerminalReporter({ isVerbose: true, showColors: true, includeStackTrace: false });
gulp.src('./spec/*.js').pipe($.jasmine({
    reporter: [terminalReporter],
    config: { spec_dir: 'spec', helpers: ['./helpers/**/*.js'] }
}))
```
