### ISSUE TITLE
Config option for custom Jasmine-instance

### ISSUE THREAD

**Issue by ulrichb** [sindresorhus/gulp-jasmine#85]
Please add a config option to be able to do the following.

```JS
var gulpJasmine = require("gulp-jasmine");
var jasmine = require('jasmine');

gulp.src("Tests.js")
  .pipe(gulpJasmine({ jasmine: jasmine }))
```

**Comment by sindresorhus** [comment]
Why?

**Comment by ulrichb** [comment]
> Why?

:smile: 

At the moment, I would need it to be able to use exactly the same Jasmine-version in the different runners (e.g. HTML runner).

It could also be used to manually downgrade the Jasmine version. E.g. would have allowed to workaround #84.

**Comment by sindresorhus** [comment]
You can already do that. Just depend on a specific Jasmine version yourself and npm@3 will deduplicate to that one, as long as it's the same major version that this plugin depends on.

More about semver: https://nodesource.com/blog/semver-tilde-and-caret

**Comment by ulrichb** [comment]
Atm I use npm 2. But OK, I think I can wait for this until I update to npm 3. 
Thanks!
