### ISSUE TITLE
Tests that should fail pass using gulp-jasmine

### ISSUE THREAD

**Issue by ArtworkAD** [sindresorhus/gulp-jasmine#88]
I have a test that fails correctly when running

`node --harmony --harmony_async_await node_modules/jasmine/bin/jasmine.js`

However the same test passes when running `gulp test` with

```
gulp.task('test', function() {
    gulp.src(['spec/**/*.spec.js']).pipe(jasmine()).pipe(exit());
});
```

Setup:

```
nodejs v7.0.0-nightly20161004e10516d5a4/

"gulp": "^3.9.1",
"gulp-nodemon": "^2.2.1",
"jasmine": "^2.5.2",
"jasmine-co": "^1.2.1",
"gulp-jasmine":"2.4.2"
```

```
spec folder:
   - helpers
         - jasmine-co.helper.js
    - integration: some integration tests
    - support
          - jasmine.json
    - unit: some unit tests
```

contents of jasmine-co.helper.js:

`require('jasmine-co').install();`

contents of jasmine.json:

```
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

I hacked up a tiny project to reproduce this problem: https://github.com/ArtworkAD/jasmine-gulp-test

```
describe('test suit', function() {
    it('true should be true', function*() {
        expect(true).toBe(false);
    });
});
```

should fail but passes!

**Comment by jbblanchet** [comment]
Hi,

We have no interest in supporting jasmine-co. If you want to submit a pull request to support it, we will consider it, but in the meantime, I'm closing this issue. Feel free to comment here if you think it should be kept open.
